# Generated by Django 5.2 on 2026-03-18 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBite_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitBite_App.orders'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitBite_App.products'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
