# Generated by Django 5.2 on 2026-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBite_App', '0002_alter_feedbacks_options_feedbacks_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dietitians/')),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dietitian',
                'verbose_name_plural': 'Dietitians',
                'ordering': ['-created_at'],
            },
        ),
    ]
