# Generated by Django 5.2 on 2026-03-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBite_App', '0003_dietitian'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_from_user', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='FitBite_App.dietitian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietitian_messages', to='FitBite_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='DietitianSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_time', models.CharField(choices=[('09:00', '09:00 AM'), ('09:30', '09:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('12:00', '12:00 PM'), ('12:30', '12:30 PM'), ('14:00', '02:00 PM'), ('14:30', '02:30 PM'), ('15:00', '03:00 PM'), ('15:30', '03:30 PM'), ('16:00', '04:00 PM'), ('16:30', '04:30 PM'), ('17:00', '05:00 PM'), ('17:30', '05:30 PM')], max_length=5)),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to='FitBite_App.user')),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='FitBite_App.dietitian')),
            ],
            options={
                'unique_together': {('dietitian', 'slot_date', 'slot_time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=20, unique=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=5)),
                ('reason', models.TextField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='FitBite_App.dietitian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='FitBite_App.user')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='FitBite_App.dietitianslot')),
            ],
        ),
        migrations.CreateModel(
            name='DietitianLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='FitBite_App.dietitian')),
            ],
            options={
                'unique_together': {('dietitian', 'leave_date')},
            },
        ),
    ]
