# Generated by Django 5.2 on 2026-03-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitBite_App', '0004_dietitianmessage_dietitianslot_appointment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietitianmessage',
            options={'ordering': ['created_at']},
        ),
    ]
