# Generated by Django 5.2 on 2026-04-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBite_App', '0006_appointment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=350.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=8),
        ),
    ]
